# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:  
- deployment: VMDeploy
  displayName: FashBash
  environment:
    name:  Deploy
    resourceType: VirtualMachine
  strategy:
    runOnce:
      preDeploy:
        steps:
          - script: sudo systemctl stop fashbash
      deploy:
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                cd /home/azureuser/FashBash
                git pull
                sudo systemctl start FashBash
      on:
          failure:
            steps:
            - script: echo Failed to deploy
          success:
            steps:
            - script: echo Succeeded


